services:
  - type: web
    name: monster-raid-server
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --worker-class sync --timeout 120 "server:Handler"
    plan: free
